INTYGFV-16522: Refactor pdf generator and add generator for Fk7443
sklintyg/core pull request #154
Opened 2024-04-19 10:03 UTC by mhornfeldt

2024-04-19 12:28 UTC, mhornfeldt commented on certificate-service/pdfbox-generator/src/main/java/se/inera/intyg/certificateservice/pdfboxgenerator/FK7211PdfGenerator.java
> +  public static final ElementId QUESTION_BERAKNAT_NEDKOMSTDATUM_ID = new ElementId("1");
Feels a bit unnatural to copy paste in the question ids here. But were in a different package and I don't think the right way to go is to add a dependency to where these ids exists. Also, I was thinking that we could programatically match the questions filled in to the fields in the pdfs. But then we would have to add the pdf field id's to the certificate model, which might also be something we don't want to do.

2024-04-22 08:24 UTC, mww-sopra-steria requested changes
Nice job on refactoring the code and increase reusability.

A few general comments to consider:
1) Look at the package structure and class names. Now it toolkit, helper, util. It doesn't say much what it is. See if you can organise it in more meaningful names. Think the comparison to legacy app using controller, service, repository etc compared to certificate, patient, unit etc. 
2) Not asking you to rewrite the code, but I think reusability increases when you try to design with pure-functions. No sideeffects. Now the interfaces takes acroform and modify it in many places. You could have changed it to gather necessary information and then have generic code filling in the pdf. Testability is also increased by doing that.
3) It is OK to use Spring in the pdf-module. Then dependency injection can be used instead of managing it within the classes itself.

2024-04-22 08:24 UTC, mww-sopra-steria commented on certificate-service/pdfbox-generator/src/main/java/se/inera/intyg/certificateservice/pdfboxgenerator/FK7211PdfFillService.java
> +public class FK7211PdfFillService implements CertificateTypePdfFillService {
Move specific certificate type code to a sub package.

2024-04-22 08:24 UTC, mww-sopra-steria commented on certificate-service/pdfbox-generator/src/test/resources/fk7443_v1.pdf
Remove pdf-files used for test. Instead add test-dependency to app-module and use the actual files. This minimises the risk of using the wrong file in test/production.

2024-04-24 09:35 UTC, mhornfeldt commented
> Nice job on refactoring the code and increase reusability.
> 
> A few general comments to consider:
> 
> 1. Look at the package structure and class names. Now it toolkit, helper, util. It doesn't say much what it is. See if you can organise it in more meaningful names. Think the comparison to legacy app using controller, service, repository etc compared to certificate, patient, unit etc.
> 2. Not asking you to rewrite the code, but I think reusability increases when you try to design with pure-functions. No sideeffects. Now the interfaces takes acroform and modify it in many places. You could have changed it to gather necessary information and then have generic code filling in the pdf. Testability is also increased by doing that.
> 3. It is OK to use Spring in the pdf-module. Then dependency injection can be used instead of managing it within the classes itself.

Fixed

2024-04-24 10:45 UTC, mww-sopra-steria approved these changes
Nice solution by introducing the "PdfField"! You have opened up new possibilities by separating the mapping to the model and the pdfbox-integration. It is also easy to read and understand the code. Well done!

Consider moving the packages "text" and "value" to "pdf" before merging.

2024-04-24 14:15 UTC, merged