INTYGFV-16529: Added storage of ExternalReference. Added errorMessage to GlobalExceptionHandlerController for CertificateActionForbidden.
sklintyg/core pull request #155
Opened 2024-04-22 13:49 UTC by ChrilleSigerhed

2024-04-22 13:56 UTC, ChrilleSigerhed commented
Example error response with two errors:

```xml
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <ns4:CreateDraftCertificateResponse>
      <ns4:result>
        <ns5:resultCode>ERROR</ns5:resultCode>
        <ns5:resultText>403 : "Du saknar behörighet för den begärda åtgärden. Det krävs särskilda rättigheter eller en specifik befattning
          för att hantera patienter med skyddade personuppgifter., Du saknar behörighet för den begärda åtgärden. Det krävs särskilda
          rättigheter eller en specifik befattning för att hantera avlidna patienter."
        </ns5:resultText>
        <ns5:errorId>VALIDATION_ERROR</ns5:errorId>
      </ns4:result>
    </ns4:CreateDraftCertificateResponse>
  </soap:Body>
</soap:Envelope>
```

2024-04-23 06:13 UTC, mww-sopra-steria requested changes
Nice work on this PR! Agree that it would be good in Webcert to remove the status-code. Also I noticed that we don't log the exception, that needs to be done! :-)

Relating to this PR there are a few minor things to look at. But also a couple of things that I would appreciate if we could discuss.

2024-04-23 06:13 UTC, mww-sopra-steria commented on certificate-service/domain/src/main/java/se/inera/intyg/certificateservice/domain/certificate/model/Certificate.java
> +  private ExternalReference externalReference;
ExternalReference is both in Certificate and CertificateMetadata. I would like to see it as part of Certificate only.

2024-04-23 06:13 UTC, mww-sopra-steria commented on certificate-service/domain/src/main/java/se/inera/intyg/certificateservice/domain/certificate/model/Certificate.java
> +        .externalReference(actionEvaluation.externalReference())
Not sure that externalReference should be updated if already provided. Do you know? Best to double check with Webcert and current implementation.

2024-04-23 06:13 UTC, mww-sopra-steria commented on certificate-service/domain/src/main/java/se/inera/intyg/certificateservice/domain/common/exception/CertificateActionForbidden.java
>    public CertificateActionForbidden(String message) {
Suggest we remove the default-constructor and force all places to provide reason.

2024-04-23 12:20 UTC, mww-sopra-steria approved these changes
Looks great! Well done!

2024-04-23 12:24 UTC, merged