INTYGFV-16699: Update FK3226 texts
sklintyg/core pull request #222
Opened 2024-07-01 07:39 UTC by SamuelTilly

2024-07-01 13:43 UTC, mhornfeldt approved these changes

2024-07-01 13:58 UTC, ChrilleSigerhed requested changes
We also need to update the following:

- Text före val av formulär
- Om intyget-text
- Ny datumbegränsning i frågan “Till och med vilket datum” - Kalenderfunktionen tillåter endast val av datum från och med det datum som angetts i tidigare fråga “Ange när tillståndet blev akut livshotande” och framåt. Dvs datum innan datumet som angetts i frågan “Ange när tillståndet blev akut livshotande” är utgråade och inte klickbara. 

The last one might need some design, so we might wanna create a separate task for this.

2024-07-02 06:49 UTC, SamuelTilly commented
> We also need to update the following:
> 
> * Text före val av formulär
> * Om intyget-text
> * Ny datumbegränsning i frågan “Till och med vilket datum” - Kalenderfunktionen tillåter endast val av datum från och med det datum som angetts i tidigare fråga “Ange när tillståndet blev akut livshotande” och framåt. Dvs datum innan datumet som angetts i frågan “Ange när tillståndet blev akut livshotande” är utgråade och inte klickbara.
> 
> The last one might need some design, so we might wanna create a separate task for this.

Fixed the first two and i split the task into separate subtasks to handle the date issue.

2024-07-02 11:04 UTC, ChrilleSigerhed approved these changes
Nice!

2024-07-02 11:14 UTC, merged