K1J-54: Implemented ready for sign end point
sklintyg/core pull request #283
Opened 2024-09-03 12:59 UTC by mhornfeldt

2024-09-03 13:05 UTC, mhornfeldt commented on certificate-service/domain/src/main/java/se/inera/intyg/certificateservice/domain/event/model/CertificateEventType.java
> +      "certificate-ready-for-sign");
Need to check this

2024-09-03 14:34 UTC, ChrilleSigerhed requested changes
This looks great, well done!

The code reads well and follows a clear structure!

Only found a little typo error, everything else looked splendid to me!

Please also add readyForSign as a field on ```CertificateMetadataDTO``` in ```CertificateMetadataConverter```

```java
.readyForSign(certificate.readyForSign().readyForSignAt())
```

2024-09-03 14:34 UTC, ChrilleSigerhed commented on certificate-service/domain/src/main/java/se/inera/intyg/certificateservice/domain/certificate/model/Certificate.java
> +          "Incorrect status '%s' - required status is '%s' to send".formatted(this.status,
Update the text to something like "...to set ready for sign"

2024-09-03 14:50 UTC, mhornfeldt commented
> This looks great, well done!
> 
> The code reads well and follows a clear structure!
> 
> Only found a little typo error, everything else looked splendid to me!
> 
> Please also add readyForSign as a field on `CertificateMetadataDTO` in `CertificateMetadataConverter`
> 
> ```java
> .readyForSign(certificate.readyForSign().readyForSignAt())
> ```

Found the missing conversion while checking the flow locally and added it but with an added null check, otherwise it won't work. Everything else seems to work locally.

2024-09-04 06:10 UTC, ChrilleSigerhed approved these changes
Looks great, well done!

2024-09-04 06:41 UTC, merged