K1J-467: Updated confirmation modal alert
sklintyg/core pull request #339
Opened 2024-11-04 07:35 UTC by mhornfeldt

2024-11-04 11:13 UTC, mww-sopra-steria requested changes
Looks good! Just one thought relating to AlertType to consider.

2024-11-04 11:13 UTC, mww-sopra-steria commented on certificate-service/domain/src/main/java/se/inera/intyg/certificateservice/domain/certificatemodel/model/AlertType.java
> +  INFO, OBSERVE, ERROR
There is something similar already in the model that is called ElementMessageLevel. Could we do something in order to use the same concept? At least within the model?

2024-11-06 08:36 UTC, ChrilleSigerhed approved these changes
Minor DTO update needed, but everything else looks good. Well done

2024-11-06 08:36 UTC, ChrilleSigerhed commented on certificate-service/app/src/main/java/se/inera/intyg/certificateservice/application/certificate/dto/AlertDTO.java
> +public class AlertDTO {
I think we need to update the AlertBuilder to AlertDTOBuilder?

2024-11-06 13:35 UTC, merged